"""empty message

Revision ID: 69f0392ecc03
Revises: 
Create Date: 2017-06-14 16:58:07.305963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69f0392ecc03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trader', sa.Column('BeginningMonthlyCharge', sa.Numeric(precision=20, scale=2, asdecimal=False), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trader', 'BeginningMonthlyCharge')
    # ### end Alembic commands ###
