"""empty message

Revision ID: 93b70dd1ff6c
Revises: 170650ed7efc
Create Date: 2017-06-16 13:00:11.177320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93b70dd1ff6c'
down_revision = '170650ed7efc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'people_addresses_association', ['Person_Oid', 'Address_Oid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'people_addresses_association', type_='unique')
    # ### end Alembic commands ###
